-- Schema drift check: lists application tables that are MISSING from this
-- database (compared to the models the API/Prisma client expect). Read-only —
-- changes nothing. A non-empty result means migrations weren't fully applied on
-- this environment; apply the corresponding supabase/migrations/*.sql, then
-- rebuild the API (npm run build regenerates the Prisma client).
--
--   psql "postgresql://USER:PASS@HOST:5432/DB" -f db/check-schema.sql
SELECT t AS missing_table
FROM unnest(ARRAY[
  'academic_calendar',
  'academic_sessions',
  'admission_enquiries',
  'admission_stage_history',
  'announcements',
  'asset_allocations',
  'asset_amc',
  'asset_categories',
  'asset_maintenance',
  'asset_vendors',
  'assets',
  'attendance',
  'attendance_corrections',
  'broadcast_recipients',
  'broadcasts',
  'candidates',
  'classes',
  'classrooms',
  'complaint_messages',
  'complaints',
  'departments',
  'designations',
  'driver_incidents',
  'drivers',
  'elective_enrollments',
  'elective_offerings',
  'exam_results',
  'exams',
  'expense_claims',
  'expenses',
  'fee_assignments',
  'fee_structures',
  'fleet_vehicles',
  'fuel_logs',
  'grievances',
  'holidays',
  'homework',
  'homework_submissions',
  'hr_appraisal_criteria',
  'hr_appraisal_cycles',
  'hr_appraisal_ratings',
  'hr_appraisals',
  'hr_employment_types',
  'hr_leave_types',
  'hr_loan_repayments',
  'hr_loans',
  'hr_pay_grades',
  'hr_salary_structures',
  'hr_salary_templates',
  'identities',
  'job_openings',
  'leave_balances',
  'leave_requests',
  'library_books',
  'library_loans',
  'overtime_requests',
  'parent_student',
  'payment_reconciliations',
  'payments',
  'payroll_runs',
  'permission_audit_log',
  'profiles',
  'progress_notes',
  'promotion_records',
  'resignations',
  'route_stops',
  'route_students',
  'shifts',
  'staff',
  'staff_documents',
  'staff_employment_history',
  'staff_permissions',
  'staff_shifts',
  'student_activity_log',
  'student_categories',
  'student_custom_fields',
  'student_details',
  'student_disciplinary',
  'student_documents',
  'student_hostel',
  'student_medical',
  'students',
  'subjects',
  'teacher_attendance',
  'teacher_classes',
  'teacher_experience',
  'teacher_performance_reviews',
  'teacher_qualifications',
  'teacher_subjects',
  'teachers',
  'timetable',
  'training_attendance',
  'training_programs',
  'transport_routes',
  'travel_requests',
  'user_roles',
  'users',
  'vehicle_documents',
  'vehicle_maintenance',
  'vehicle_positions',
  'visitor_logs'
]) AS t
WHERE NOT EXISTS (
  SELECT 1 FROM information_schema.tables it
  WHERE it.table_name = t AND it.table_schema IN ('public','auth')
)
ORDER BY 1;
