-- Additive schema reconciliation: ensures every application column exists on
-- this database, with the correct type and default. Generated from the reference
-- schema. It ONLY adds missing columns (ADD COLUMN IF NOT EXISTS) — it never
-- drops or alters existing columns, and it never touches data. Safe to run on a
-- populated production database, and idempotent (re-running is a no-op).
--
-- Use this to clear the "Database error" that appears when a table is missing a
-- column the app expects (Prisma P2022) — e.g. Add Vehicle, New Department, New
-- Job Opening. It does NOT create missing *tables*; if db/check-schema.sql
-- reports a missing table, apply that table's supabase/migrations/*.sql first.
--
-- psql keeps going past any "relation does not exist" notice (for a table that
-- isn't present yet), so a few such notices are harmless.
--
--   psql "postgresql://USER:PASS@HOST:5432/DB" -f db/reconcile-columns.sql
ALTER TABLE public.academic_calendar ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.academic_calendar ADD COLUMN IF NOT EXISTS session text;
ALTER TABLE public.academic_calendar ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.academic_calendar ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.academic_calendar ADD COLUMN IF NOT EXISTS event_type text DEFAULT 'event'::text;
ALTER TABLE public.academic_calendar ADD COLUMN IF NOT EXISTS start_date date;
ALTER TABLE public.academic_calendar ADD COLUMN IF NOT EXISTS end_date date;
ALTER TABLE public.academic_calendar ADD COLUMN IF NOT EXISTS created_by uuid;
ALTER TABLE public.academic_calendar ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.academic_calendar ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.academic_sessions ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.academic_sessions ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.academic_sessions ADD COLUMN IF NOT EXISTS start_date date;
ALTER TABLE public.academic_sessions ADD COLUMN IF NOT EXISTS end_date date;
ALTER TABLE public.academic_sessions ADD COLUMN IF NOT EXISTS is_current boolean DEFAULT false;
ALTER TABLE public.academic_sessions ADD COLUMN IF NOT EXISTS status text DEFAULT 'active'::text;
ALTER TABLE public.academic_sessions ADD COLUMN IF NOT EXISTS board text;
ALTER TABLE public.academic_sessions ADD COLUMN IF NOT EXISTS curriculum text;
ALTER TABLE public.academic_sessions ADD COLUMN IF NOT EXISTS promotion_locked boolean DEFAULT false;
ALTER TABLE public.academic_sessions ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.academic_sessions ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS student_name text;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS parent_name text;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS parent_phone text;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS parent_email text;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS grade_applying text;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS enquiry_date date DEFAULT CURRENT_DATE;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS status text DEFAULT 'new'::text;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS converted_student_id uuid;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS admission_no text;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS stage text DEFAULT 'draft'::text;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS applicant_dob date;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS applicant_gender text;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS applicant_address text;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS previous_school text;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS blood_group text;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS transport_required boolean DEFAULT false;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS hostel_required boolean DEFAULT false;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS medical_notes text;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS academic_year text;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS class_id uuid;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS section text;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS fee_structure_id uuid;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS parent_id uuid;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS reviewer_id uuid;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS rejection_reason text;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS submitted_at timestamp with time zone;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS approved_at timestamp with time zone;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS admitted_at timestamp with time zone;
ALTER TABLE public.admission_enquiries ADD COLUMN IF NOT EXISTS documents jsonb DEFAULT '[]'::jsonb;
ALTER TABLE public.admission_stage_history ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.admission_stage_history ADD COLUMN IF NOT EXISTS admission_id uuid;
ALTER TABLE public.admission_stage_history ADD COLUMN IF NOT EXISTS from_stage text;
ALTER TABLE public.admission_stage_history ADD COLUMN IF NOT EXISTS to_stage text;
ALTER TABLE public.admission_stage_history ADD COLUMN IF NOT EXISTS actor_id uuid;
ALTER TABLE public.admission_stage_history ADD COLUMN IF NOT EXISTS note text;
ALTER TABLE public.admission_stage_history ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS body text;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS audience announcement_audience DEFAULT 'all'::announcement_audience;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS class_id uuid;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS author_id uuid;
ALTER TABLE public.announcements ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.asset_allocations ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.asset_allocations ADD COLUMN IF NOT EXISTS asset_id uuid;
ALTER TABLE public.asset_allocations ADD COLUMN IF NOT EXISTS assignee_profile_id uuid;
ALTER TABLE public.asset_allocations ADD COLUMN IF NOT EXISTS assignee_label text;
ALTER TABLE public.asset_allocations ADD COLUMN IF NOT EXISTS allocated_at date DEFAULT CURRENT_DATE;
ALTER TABLE public.asset_allocations ADD COLUMN IF NOT EXISTS expected_return_at date;
ALTER TABLE public.asset_allocations ADD COLUMN IF NOT EXISTS returned_at date;
ALTER TABLE public.asset_allocations ADD COLUMN IF NOT EXISTS return_condition text;
ALTER TABLE public.asset_allocations ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.asset_allocations ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.asset_allocations ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.asset_amc ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.asset_amc ADD COLUMN IF NOT EXISTS asset_id uuid;
ALTER TABLE public.asset_amc ADD COLUMN IF NOT EXISTS vendor_id uuid;
ALTER TABLE public.asset_amc ADD COLUMN IF NOT EXISTS start_date date;
ALTER TABLE public.asset_amc ADD COLUMN IF NOT EXISTS end_date date;
ALTER TABLE public.asset_amc ADD COLUMN IF NOT EXISTS coverage text;
ALTER TABLE public.asset_amc ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.asset_amc ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.asset_amc ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.asset_categories ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.asset_categories ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.asset_categories ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.asset_categories ADD COLUMN IF NOT EXISTS created_by uuid;
ALTER TABLE public.asset_categories ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.asset_categories ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.asset_maintenance ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.asset_maintenance ADD COLUMN IF NOT EXISTS asset_id uuid;
ALTER TABLE public.asset_maintenance ADD COLUMN IF NOT EXISTS scheduled_for date;
ALTER TABLE public.asset_maintenance ADD COLUMN IF NOT EXISTS completed_at date;
ALTER TABLE public.asset_maintenance ADD COLUMN IF NOT EXISTS type text DEFAULT 'general'::text;
ALTER TABLE public.asset_maintenance ADD COLUMN IF NOT EXISTS cost numeric(12,2) DEFAULT 0;
ALTER TABLE public.asset_maintenance ADD COLUMN IF NOT EXISTS performed_by text;
ALTER TABLE public.asset_maintenance ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.asset_maintenance ADD COLUMN IF NOT EXISTS status text DEFAULT 'scheduled'::text;
ALTER TABLE public.asset_maintenance ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.asset_maintenance ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.asset_vendors ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.asset_vendors ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.asset_vendors ADD COLUMN IF NOT EXISTS contact_name text;
ALTER TABLE public.asset_vendors ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE public.asset_vendors ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE public.asset_vendors ADD COLUMN IF NOT EXISTS category_hint text;
ALTER TABLE public.asset_vendors ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.asset_vendors ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS location text;
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS condition text DEFAULT 'good'::text;
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS status text DEFAULT 'available'::text;
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS asset_code text;
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS category_id uuid;
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS vendor_id uuid;
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS purchase_date date;
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS purchase_price numeric(12,2);
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS current_value numeric(12,2);
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS warranty_expiry date;
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS invoice_ref text;
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS qr_value text;
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS barcode_value text;
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS useful_life_years integer DEFAULT 5;
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS assigned_to_profile_id uuid;
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS assigned_to_label text;
ALTER TABLE public.assets ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS student_id uuid;
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS class_id uuid;
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS date date;
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS status attendance_status DEFAULT 'present'::attendance_status;
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS marked_by uuid;
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS note text;
ALTER TABLE public.attendance ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.attendance_corrections ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.attendance_corrections ADD COLUMN IF NOT EXISTS attendance_id uuid;
ALTER TABLE public.attendance_corrections ADD COLUMN IF NOT EXISTS teacher_id uuid;
ALTER TABLE public.attendance_corrections ADD COLUMN IF NOT EXISTS date date;
ALTER TABLE public.attendance_corrections ADD COLUMN IF NOT EXISTS from_status text;
ALTER TABLE public.attendance_corrections ADD COLUMN IF NOT EXISTS to_status text;
ALTER TABLE public.attendance_corrections ADD COLUMN IF NOT EXISTS from_check_in timestamp with time zone;
ALTER TABLE public.attendance_corrections ADD COLUMN IF NOT EXISTS to_check_in timestamp with time zone;
ALTER TABLE public.attendance_corrections ADD COLUMN IF NOT EXISTS reason text;
ALTER TABLE public.attendance_corrections ADD COLUMN IF NOT EXISTS changed_by uuid;
ALTER TABLE public.attendance_corrections ADD COLUMN IF NOT EXISTS changed_by_role text;
ALTER TABLE public.attendance_corrections ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.broadcast_recipients ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.broadcast_recipients ADD COLUMN IF NOT EXISTS broadcast_id uuid;
ALTER TABLE public.broadcast_recipients ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE public.broadcast_recipients ADD COLUMN IF NOT EXISTS read_at timestamp with time zone;
ALTER TABLE public.broadcast_recipients ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.broadcasts ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.broadcasts ADD COLUMN IF NOT EXISTS sender_id uuid;
ALTER TABLE public.broadcasts ADD COLUMN IF NOT EXISTS audience_type text;
ALTER TABLE public.broadcasts ADD COLUMN IF NOT EXISTS audience_ref uuid;
ALTER TABLE public.broadcasts ADD COLUMN IF NOT EXISTS subject text;
ALTER TABLE public.broadcasts ADD COLUMN IF NOT EXISTS body text;
ALTER TABLE public.broadcasts ADD COLUMN IF NOT EXISTS attachment_url text;
ALTER TABLE public.broadcasts ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.broadcasts ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.candidates ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.candidates ADD COLUMN IF NOT EXISTS job_opening_id uuid;
ALTER TABLE public.candidates ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.candidates ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE public.candidates ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE public.candidates ADD COLUMN IF NOT EXISTS resume_url text;
ALTER TABLE public.candidates ADD COLUMN IF NOT EXISTS stage text DEFAULT 'applied'::text;
ALTER TABLE public.candidates ADD COLUMN IF NOT EXISTS source text;
ALTER TABLE public.candidates ADD COLUMN IF NOT EXISTS rating integer;
ALTER TABLE public.candidates ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.candidates ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.candidates ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS section text;
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS academic_year text DEFAULT '2025-2026'::text;
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS capacity integer;
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS room text;
ALTER TABLE public.classes ADD COLUMN IF NOT EXISTS class_teacher_id uuid;
ALTER TABLE public.classrooms ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.classrooms ADD COLUMN IF NOT EXISTS room_number text;
ALTER TABLE public.classrooms ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.classrooms ADD COLUMN IF NOT EXISTS capacity integer DEFAULT 40;
ALTER TABLE public.classrooms ADD COLUMN IF NOT EXISTS floor text;
ALTER TABLE public.classrooms ADD COLUMN IF NOT EXISTS building text;
ALTER TABLE public.classrooms ADD COLUMN IF NOT EXISTS room_type text DEFAULT 'classroom'::text;
ALTER TABLE public.classrooms ADD COLUMN IF NOT EXISTS is_smart boolean DEFAULT false;
ALTER TABLE public.classrooms ADD COLUMN IF NOT EXISTS has_projector boolean DEFAULT false;
ALTER TABLE public.classrooms ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE public.classrooms ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.classrooms ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.complaint_messages ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.complaint_messages ADD COLUMN IF NOT EXISTS complaint_id uuid;
ALTER TABLE public.complaint_messages ADD COLUMN IF NOT EXISTS sender_id uuid;
ALTER TABLE public.complaint_messages ADD COLUMN IF NOT EXISTS body text;
ALTER TABLE public.complaint_messages ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS student_id uuid;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS raised_by uuid;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS subject text;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS body text;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS severity text DEFAULT 'low'::text;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS status text DEFAULT 'open'::text;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS escalated_to_admin boolean DEFAULT false;
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.complaints ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.departments ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.departments ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.departments ADD COLUMN IF NOT EXISTS code text;
ALTER TABLE public.departments ADD COLUMN IF NOT EXISTS head_staff_id uuid;
ALTER TABLE public.departments ADD COLUMN IF NOT EXISTS budget numeric DEFAULT 0;
ALTER TABLE public.departments ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.departments ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.departments ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.designations ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.designations ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.designations ADD COLUMN IF NOT EXISTS department_id uuid;
ALTER TABLE public.designations ADD COLUMN IF NOT EXISTS level integer DEFAULT 1;
ALTER TABLE public.designations ADD COLUMN IF NOT EXISTS salary_grade text;
ALTER TABLE public.designations ADD COLUMN IF NOT EXISTS min_pay numeric;
ALTER TABLE public.designations ADD COLUMN IF NOT EXISTS max_pay numeric;
ALTER TABLE public.designations ADD COLUMN IF NOT EXISTS reports_to uuid;
ALTER TABLE public.designations ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.driver_incidents ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.driver_incidents ADD COLUMN IF NOT EXISTS driver_id uuid;
ALTER TABLE public.driver_incidents ADD COLUMN IF NOT EXISTS incident_date date DEFAULT CURRENT_DATE;
ALTER TABLE public.driver_incidents ADD COLUMN IF NOT EXISTS incident_type text;
ALTER TABLE public.driver_incidents ADD COLUMN IF NOT EXISTS severity text DEFAULT 'low'::text;
ALTER TABLE public.driver_incidents ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.driver_incidents ADD COLUMN IF NOT EXISTS reported_by uuid;
ALTER TABLE public.driver_incidents ADD COLUMN IF NOT EXISTS status text DEFAULT 'open'::text;
ALTER TABLE public.driver_incidents ADD COLUMN IF NOT EXISTS resolution_notes text;
ALTER TABLE public.driver_incidents ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.driver_incidents ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS full_name text;
ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS license_no text;
ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS license_expiry date;
ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS years_experience integer DEFAULT 0;
ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS assigned_vehicle_id uuid;
ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.drivers ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.elective_enrollments ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.elective_enrollments ADD COLUMN IF NOT EXISTS offering_id uuid;
ALTER TABLE public.elective_enrollments ADD COLUMN IF NOT EXISTS student_id uuid;
ALTER TABLE public.elective_enrollments ADD COLUMN IF NOT EXISTS status text DEFAULT 'enrolled'::text;
ALTER TABLE public.elective_enrollments ADD COLUMN IF NOT EXISTS enrolled_at timestamp with time zone DEFAULT now();
ALTER TABLE public.elective_offerings ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.elective_offerings ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.elective_offerings ADD COLUMN IF NOT EXISTS code text;
ALTER TABLE public.elective_offerings ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.elective_offerings ADD COLUMN IF NOT EXISTS session text;
ALTER TABLE public.elective_offerings ADD COLUMN IF NOT EXISTS grade_level text;
ALTER TABLE public.elective_offerings ADD COLUMN IF NOT EXISTS seat_capacity integer DEFAULT 30;
ALTER TABLE public.elective_offerings ADD COLUMN IF NOT EXISTS subject_id uuid;
ALTER TABLE public.elective_offerings ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE public.elective_offerings ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.elective_offerings ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS exam_id uuid;
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS student_id uuid;
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS marks_obtained numeric DEFAULT 0;
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS grade text;
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS remarks text;
ALTER TABLE public.exam_results ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.exams ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.exams ADD COLUMN IF NOT EXISTS class_id uuid;
ALTER TABLE public.exams ADD COLUMN IF NOT EXISTS subject_id uuid;
ALTER TABLE public.exams ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.exams ADD COLUMN IF NOT EXISTS exam_date date;
ALTER TABLE public.exams ADD COLUMN IF NOT EXISTS max_marks numeric DEFAULT 100;
ALTER TABLE public.exams ADD COLUMN IF NOT EXISTS term text;
ALTER TABLE public.exams ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.expense_claims ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.expense_claims ADD COLUMN IF NOT EXISTS staff_id uuid;
ALTER TABLE public.expense_claims ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE public.expense_claims ADD COLUMN IF NOT EXISTS amount numeric DEFAULT 0;
ALTER TABLE public.expense_claims ADD COLUMN IF NOT EXISTS claim_date date DEFAULT CURRENT_DATE;
ALTER TABLE public.expense_claims ADD COLUMN IF NOT EXISTS receipt_url text;
ALTER TABLE public.expense_claims ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending'::text;
ALTER TABLE public.expense_claims ADD COLUMN IF NOT EXISTS approver_id uuid;
ALTER TABLE public.expense_claims ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.expense_claims ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.expense_claims ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS vendor text;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS amount numeric(12,2);
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS expense_date date;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS approval_status text DEFAULT 'approved'::text;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS created_by uuid;
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.expenses ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.fee_assignments ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.fee_assignments ADD COLUMN IF NOT EXISTS student_id uuid;
ALTER TABLE public.fee_assignments ADD COLUMN IF NOT EXISTS structure_id uuid;
ALTER TABLE public.fee_assignments ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.fee_assignments ADD COLUMN IF NOT EXISTS amount_due numeric(10,2);
ALTER TABLE public.fee_assignments ADD COLUMN IF NOT EXISTS amount_paid numeric(10,2) DEFAULT 0;
ALTER TABLE public.fee_assignments ADD COLUMN IF NOT EXISTS due_date date;
ALTER TABLE public.fee_assignments ADD COLUMN IF NOT EXISTS status fee_status DEFAULT 'pending'::fee_status;
ALTER TABLE public.fee_assignments ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.fee_structures ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.fee_structures ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.fee_structures ADD COLUMN IF NOT EXISTS class_id uuid;
ALTER TABLE public.fee_structures ADD COLUMN IF NOT EXISTS amount numeric(10,2);
ALTER TABLE public.fee_structures ADD COLUMN IF NOT EXISTS term text;
ALTER TABLE public.fee_structures ADD COLUMN IF NOT EXISTS academic_year text DEFAULT '2025-2026'::text;
ALTER TABLE public.fee_structures ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.fee_structures ADD COLUMN IF NOT EXISTS frequency fee_frequency DEFAULT 'one_time'::fee_frequency;
ALTER TABLE public.fleet_vehicles ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.fleet_vehicles ADD COLUMN IF NOT EXISTS registration_no text;
ALTER TABLE public.fleet_vehicles ADD COLUMN IF NOT EXISTS vehicle_type text DEFAULT 'bus'::text;
ALTER TABLE public.fleet_vehicles ADD COLUMN IF NOT EXISTS model text;
ALTER TABLE public.fleet_vehicles ADD COLUMN IF NOT EXISTS capacity integer DEFAULT 40;
ALTER TABLE public.fleet_vehicles ADD COLUMN IF NOT EXISTS purchase_date date;
ALTER TABLE public.fleet_vehicles ADD COLUMN IF NOT EXISTS insurance_expiry date;
ALTER TABLE public.fleet_vehicles ADD COLUMN IF NOT EXISTS permit_expiry date;
ALTER TABLE public.fleet_vehicles ADD COLUMN IF NOT EXISTS status text DEFAULT 'active'::text;
ALTER TABLE public.fleet_vehicles ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.fleet_vehicles ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.fuel_logs ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.fuel_logs ADD COLUMN IF NOT EXISTS vehicle_id uuid;
ALTER TABLE public.fuel_logs ADD COLUMN IF NOT EXISTS date date;
ALTER TABLE public.fuel_logs ADD COLUMN IF NOT EXISTS liters numeric(10,2);
ALTER TABLE public.fuel_logs ADD COLUMN IF NOT EXISTS cost numeric(12,2);
ALTER TABLE public.fuel_logs ADD COLUMN IF NOT EXISTS odometer integer;
ALTER TABLE public.fuel_logs ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.fuel_logs ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.grievances ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.grievances ADD COLUMN IF NOT EXISTS staff_id uuid;
ALTER TABLE public.grievances ADD COLUMN IF NOT EXISTS subject text;
ALTER TABLE public.grievances ADD COLUMN IF NOT EXISTS message text;
ALTER TABLE public.grievances ADD COLUMN IF NOT EXISTS status text DEFAULT 'open'::text;
ALTER TABLE public.grievances ADD COLUMN IF NOT EXISTS response text;
ALTER TABLE public.grievances ADD COLUMN IF NOT EXISTS resolved_at timestamp with time zone;
ALTER TABLE public.grievances ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.holidays ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.holidays ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.holidays ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.holidays ADD COLUMN IF NOT EXISTS start_date date;
ALTER TABLE public.holidays ADD COLUMN IF NOT EXISTS end_date date;
ALTER TABLE public.holidays ADD COLUMN IF NOT EXISTS type holiday_type DEFAULT 'holiday'::holiday_type;
ALTER TABLE public.holidays ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.holidays ADD COLUMN IF NOT EXISTS created_by uuid;
ALTER TABLE public.homework ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.homework ADD COLUMN IF NOT EXISTS class_id uuid;
ALTER TABLE public.homework ADD COLUMN IF NOT EXISTS subject_id uuid;
ALTER TABLE public.homework ADD COLUMN IF NOT EXISTS teacher_id uuid;
ALTER TABLE public.homework ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.homework ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.homework ADD COLUMN IF NOT EXISTS assigned_date date DEFAULT CURRENT_DATE;
ALTER TABLE public.homework ADD COLUMN IF NOT EXISTS due_date date;
ALTER TABLE public.homework ADD COLUMN IF NOT EXISTS status text DEFAULT 'active'::text;
ALTER TABLE public.homework ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.homework ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.homework ADD COLUMN IF NOT EXISTS priority text DEFAULT 'medium'::text;
ALTER TABLE public.homework ADD COLUMN IF NOT EXISTS attachment_url text;
ALTER TABLE public.homework ADD COLUMN IF NOT EXISTS attachment_type text;
ALTER TABLE public.homework ADD COLUMN IF NOT EXISTS max_marks numeric;
ALTER TABLE public.homework_submissions ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.homework_submissions ADD COLUMN IF NOT EXISTS homework_id uuid;
ALTER TABLE public.homework_submissions ADD COLUMN IF NOT EXISTS student_id uuid;
ALTER TABLE public.homework_submissions ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending'::text;
ALTER TABLE public.homework_submissions ADD COLUMN IF NOT EXISTS submitted_at timestamp with time zone;
ALTER TABLE public.homework_submissions ADD COLUMN IF NOT EXISTS attachment_url text;
ALTER TABLE public.homework_submissions ADD COLUMN IF NOT EXISTS note text;
ALTER TABLE public.homework_submissions ADD COLUMN IF NOT EXISTS marks numeric;
ALTER TABLE public.homework_submissions ADD COLUMN IF NOT EXISTS remarks text;
ALTER TABLE public.homework_submissions ADD COLUMN IF NOT EXISTS reviewed_at timestamp with time zone;
ALTER TABLE public.homework_submissions ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.homework_submissions ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.hr_appraisal_criteria ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.hr_appraisal_criteria ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.hr_appraisal_criteria ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.hr_appraisal_criteria ADD COLUMN IF NOT EXISTS weight numeric(6,2) DEFAULT 1;
ALTER TABLE public.hr_appraisal_criteria ADD COLUMN IF NOT EXISTS max_score integer DEFAULT 5;
ALTER TABLE public.hr_appraisal_criteria ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE public.hr_appraisal_criteria ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.hr_appraisal_cycles ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.hr_appraisal_cycles ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.hr_appraisal_cycles ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.hr_appraisal_cycles ADD COLUMN IF NOT EXISTS period_start date;
ALTER TABLE public.hr_appraisal_cycles ADD COLUMN IF NOT EXISTS period_end date;
ALTER TABLE public.hr_appraisal_cycles ADD COLUMN IF NOT EXISTS status text DEFAULT 'draft'::text;
ALTER TABLE public.hr_appraisal_cycles ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.hr_appraisal_cycles ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.hr_appraisal_ratings ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.hr_appraisal_ratings ADD COLUMN IF NOT EXISTS appraisal_id uuid;
ALTER TABLE public.hr_appraisal_ratings ADD COLUMN IF NOT EXISTS criterion_id uuid;
ALTER TABLE public.hr_appraisal_ratings ADD COLUMN IF NOT EXISTS score numeric(6,2) DEFAULT 0;
ALTER TABLE public.hr_appraisal_ratings ADD COLUMN IF NOT EXISTS comments text;
ALTER TABLE public.hr_appraisal_ratings ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.hr_appraisals ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.hr_appraisals ADD COLUMN IF NOT EXISTS cycle_id uuid;
ALTER TABLE public.hr_appraisals ADD COLUMN IF NOT EXISTS staff_id uuid;
ALTER TABLE public.hr_appraisals ADD COLUMN IF NOT EXISTS reviewer_id uuid;
ALTER TABLE public.hr_appraisals ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending'::text;
ALTER TABLE public.hr_appraisals ADD COLUMN IF NOT EXISTS overall_score numeric(6,2);
ALTER TABLE public.hr_appraisals ADD COLUMN IF NOT EXISTS self_comments text;
ALTER TABLE public.hr_appraisals ADD COLUMN IF NOT EXISTS manager_comments text;
ALTER TABLE public.hr_appraisals ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.hr_appraisals ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.hr_employment_types ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.hr_employment_types ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.hr_employment_types ADD COLUMN IF NOT EXISTS code text;
ALTER TABLE public.hr_employment_types ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE public.hr_employment_types ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.hr_leave_types ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.hr_leave_types ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.hr_leave_types ADD COLUMN IF NOT EXISTS code text;
ALTER TABLE public.hr_leave_types ADD COLUMN IF NOT EXISTS annual_quota integer DEFAULT 0;
ALTER TABLE public.hr_leave_types ADD COLUMN IF NOT EXISTS is_paid boolean DEFAULT true;
ALTER TABLE public.hr_leave_types ADD COLUMN IF NOT EXISTS carry_forward boolean DEFAULT false;
ALTER TABLE public.hr_leave_types ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE public.hr_leave_types ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.hr_loan_repayments ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.hr_loan_repayments ADD COLUMN IF NOT EXISTS loan_id uuid;
ALTER TABLE public.hr_loan_repayments ADD COLUMN IF NOT EXISTS amount numeric(12,2);
ALTER TABLE public.hr_loan_repayments ADD COLUMN IF NOT EXISTS paid_on date DEFAULT CURRENT_DATE;
ALTER TABLE public.hr_loan_repayments ADD COLUMN IF NOT EXISTS installment_no integer;
ALTER TABLE public.hr_loan_repayments ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.hr_loan_repayments ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.hr_loans ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.hr_loans ADD COLUMN IF NOT EXISTS staff_id uuid;
ALTER TABLE public.hr_loans ADD COLUMN IF NOT EXISTS loan_type text DEFAULT 'advance'::text;
ALTER TABLE public.hr_loans ADD COLUMN IF NOT EXISTS principal numeric(12,2);
ALTER TABLE public.hr_loans ADD COLUMN IF NOT EXISTS interest_rate numeric(6,3) DEFAULT 0;
ALTER TABLE public.hr_loans ADD COLUMN IF NOT EXISTS tenure_months integer DEFAULT 1;
ALTER TABLE public.hr_loans ADD COLUMN IF NOT EXISTS reason text;
ALTER TABLE public.hr_loans ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending'::text;
ALTER TABLE public.hr_loans ADD COLUMN IF NOT EXISTS disbursed_on date;
ALTER TABLE public.hr_loans ADD COLUMN IF NOT EXISTS approved_by uuid;
ALTER TABLE public.hr_loans ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.hr_loans ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.hr_pay_grades ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.hr_pay_grades ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.hr_pay_grades ADD COLUMN IF NOT EXISTS code text;
ALTER TABLE public.hr_pay_grades ADD COLUMN IF NOT EXISTS level integer DEFAULT 1;
ALTER TABLE public.hr_pay_grades ADD COLUMN IF NOT EXISTS min_salary numeric;
ALTER TABLE public.hr_pay_grades ADD COLUMN IF NOT EXISTS max_salary numeric;
ALTER TABLE public.hr_pay_grades ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE public.hr_pay_grades ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.hr_salary_structures ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.hr_salary_structures ADD COLUMN IF NOT EXISTS staff_id uuid;
ALTER TABLE public.hr_salary_structures ADD COLUMN IF NOT EXISTS template_id uuid;
ALTER TABLE public.hr_salary_structures ADD COLUMN IF NOT EXISTS basic numeric(12,2) DEFAULT 0;
ALTER TABLE public.hr_salary_structures ADD COLUMN IF NOT EXISTS earnings jsonb DEFAULT '[]'::jsonb;
ALTER TABLE public.hr_salary_structures ADD COLUMN IF NOT EXISTS deductions jsonb DEFAULT '[]'::jsonb;
ALTER TABLE public.hr_salary_structures ADD COLUMN IF NOT EXISTS pf_enabled boolean DEFAULT true;
ALTER TABLE public.hr_salary_structures ADD COLUMN IF NOT EXISTS esi_enabled boolean DEFAULT true;
ALTER TABLE public.hr_salary_structures ADD COLUMN IF NOT EXISTS pt_enabled boolean DEFAULT true;
ALTER TABLE public.hr_salary_structures ADD COLUMN IF NOT EXISTS tds_enabled boolean DEFAULT false;
ALTER TABLE public.hr_salary_structures ADD COLUMN IF NOT EXISTS tds_amount numeric(12,2) DEFAULT 0;
ALTER TABLE public.hr_salary_structures ADD COLUMN IF NOT EXISTS effective_from date DEFAULT CURRENT_DATE;
ALTER TABLE public.hr_salary_structures ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.hr_salary_structures ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.hr_salary_structures ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.hr_salary_templates ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.hr_salary_templates ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.hr_salary_templates ADD COLUMN IF NOT EXISTS code text;
ALTER TABLE public.hr_salary_templates ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.hr_salary_templates ADD COLUMN IF NOT EXISTS basic numeric(12,2) DEFAULT 0;
ALTER TABLE public.hr_salary_templates ADD COLUMN IF NOT EXISTS earnings jsonb DEFAULT '[]'::jsonb;
ALTER TABLE public.hr_salary_templates ADD COLUMN IF NOT EXISTS deductions jsonb DEFAULT '[]'::jsonb;
ALTER TABLE public.hr_salary_templates ADD COLUMN IF NOT EXISTS pf_enabled boolean DEFAULT true;
ALTER TABLE public.hr_salary_templates ADD COLUMN IF NOT EXISTS esi_enabled boolean DEFAULT true;
ALTER TABLE public.hr_salary_templates ADD COLUMN IF NOT EXISTS pt_enabled boolean DEFAULT true;
ALTER TABLE public.hr_salary_templates ADD COLUMN IF NOT EXISTS tds_enabled boolean DEFAULT false;
ALTER TABLE public.hr_salary_templates ADD COLUMN IF NOT EXISTS tds_amount numeric(12,2) DEFAULT 0;
ALTER TABLE public.hr_salary_templates ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE public.hr_salary_templates ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.hr_salary_templates ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.job_openings ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.job_openings ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.job_openings ADD COLUMN IF NOT EXISTS department text;
ALTER TABLE public.job_openings ADD COLUMN IF NOT EXISTS positions integer DEFAULT 1;
ALTER TABLE public.job_openings ADD COLUMN IF NOT EXISTS status text DEFAULT 'open'::text;
ALTER TABLE public.job_openings ADD COLUMN IF NOT EXISTS opened_at date DEFAULT CURRENT_DATE;
ALTER TABLE public.job_openings ADD COLUMN IF NOT EXISTS closes_at date;
ALTER TABLE public.job_openings ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.job_openings ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.leave_balances ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.leave_balances ADD COLUMN IF NOT EXISTS staff_id uuid;
ALTER TABLE public.leave_balances ADD COLUMN IF NOT EXISTS year integer;
ALTER TABLE public.leave_balances ADD COLUMN IF NOT EXISTS leave_type text;
ALTER TABLE public.leave_balances ADD COLUMN IF NOT EXISTS allotted integer DEFAULT 0;
ALTER TABLE public.leave_balances ADD COLUMN IF NOT EXISTS used integer DEFAULT 0;
ALTER TABLE public.leave_balances ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.leave_balances ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS staff_id uuid;
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS leave_type text;
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS start_date date;
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS end_date date;
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS days integer;
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending'::text;
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS reason text;
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS approver_id uuid;
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS approver_comment text;
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS decided_at timestamp with time zone;
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.leave_requests ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.library_books ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.library_books ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.library_books ADD COLUMN IF NOT EXISTS author text;
ALTER TABLE public.library_books ADD COLUMN IF NOT EXISTS isbn text;
ALTER TABLE public.library_books ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE public.library_books ADD COLUMN IF NOT EXISTS total_copies integer DEFAULT 1;
ALTER TABLE public.library_books ADD COLUMN IF NOT EXISTS available_copies integer DEFAULT 1;
ALTER TABLE public.library_books ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.library_books ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.library_loans ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.library_loans ADD COLUMN IF NOT EXISTS book_id uuid;
ALTER TABLE public.library_loans ADD COLUMN IF NOT EXISTS student_id uuid;
ALTER TABLE public.library_loans ADD COLUMN IF NOT EXISTS issued_at timestamp with time zone DEFAULT now();
ALTER TABLE public.library_loans ADD COLUMN IF NOT EXISTS due_at date;
ALTER TABLE public.library_loans ADD COLUMN IF NOT EXISTS returned_at timestamp with time zone;
ALTER TABLE public.library_loans ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.library_loans ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.library_loans ADD COLUMN IF NOT EXISTS borrower_type text DEFAULT 'student'::text;
ALTER TABLE public.library_loans ADD COLUMN IF NOT EXISTS teacher_id uuid;
ALTER TABLE public.library_loans ADD COLUMN IF NOT EXISTS fine_amount numeric DEFAULT 0;
ALTER TABLE public.library_loans ADD COLUMN IF NOT EXISTS fine_status text DEFAULT 'none'::text;
ALTER TABLE public.library_loans ADD COLUMN IF NOT EXISTS fine_settled_at timestamp with time zone;
ALTER TABLE public.library_loans ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.overtime_requests ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.overtime_requests ADD COLUMN IF NOT EXISTS staff_id uuid;
ALTER TABLE public.overtime_requests ADD COLUMN IF NOT EXISTS work_date date;
ALTER TABLE public.overtime_requests ADD COLUMN IF NOT EXISTS hours numeric DEFAULT 0;
ALTER TABLE public.overtime_requests ADD COLUMN IF NOT EXISTS rate_multiplier numeric DEFAULT 1.5;
ALTER TABLE public.overtime_requests ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending'::text;
ALTER TABLE public.overtime_requests ADD COLUMN IF NOT EXISTS approver_id uuid;
ALTER TABLE public.overtime_requests ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.overtime_requests ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.parent_student ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.parent_student ADD COLUMN IF NOT EXISTS parent_id uuid;
ALTER TABLE public.parent_student ADD COLUMN IF NOT EXISTS student_id uuid;
ALTER TABLE public.parent_student ADD COLUMN IF NOT EXISTS relationship text DEFAULT 'parent'::text;
ALTER TABLE public.parent_student ADD COLUMN IF NOT EXISTS relationship_type text DEFAULT 'guardian'::text;
ALTER TABLE public.parent_student ADD COLUMN IF NOT EXISTS is_primary boolean DEFAULT false;
ALTER TABLE public.parent_student ADD COLUMN IF NOT EXISTS pickup_permission boolean DEFAULT false;
ALTER TABLE public.parent_student ADD COLUMN IF NOT EXISTS fee_responsible boolean DEFAULT false;
ALTER TABLE public.parent_student ADD COLUMN IF NOT EXISTS emergency_contact boolean DEFAULT false;
ALTER TABLE public.parent_student ADD COLUMN IF NOT EXISTS lives_with boolean DEFAULT false;
ALTER TABLE public.parent_student ADD COLUMN IF NOT EXISTS status text DEFAULT 'active'::text;
ALTER TABLE public.payment_reconciliations ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.payment_reconciliations ADD COLUMN IF NOT EXISTS payment_id uuid;
ALTER TABLE public.payment_reconciliations ADD COLUMN IF NOT EXISTS bank_ref text;
ALTER TABLE public.payment_reconciliations ADD COLUMN IF NOT EXISTS reconciled_at timestamp with time zone DEFAULT now();
ALTER TABLE public.payment_reconciliations ADD COLUMN IF NOT EXISTS reconciled_by uuid;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS fee_assignment_id uuid;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS student_id uuid;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS amount numeric(10,2);
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS method text DEFAULT 'manual'::text;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS reference text;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS receipt_no text DEFAULT ((('RCPT-'::text || to_char(now(), 'YYYYMMDD'::text)) || '-'::text) || substr((gen_random_uuid())::text, 1, 8));
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS paid_at timestamp with time zone DEFAULT now();
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS recorded_by uuid;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS status payment_status DEFAULT 'successful'::payment_status;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS payment_source text DEFAULT 'offline'::text;
ALTER TABLE public.payments ADD COLUMN IF NOT EXISTS proof_url text;
ALTER TABLE public.payroll_runs ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.payroll_runs ADD COLUMN IF NOT EXISTS staff_id uuid;
ALTER TABLE public.payroll_runs ADD COLUMN IF NOT EXISTS month date;
ALTER TABLE public.payroll_runs ADD COLUMN IF NOT EXISTS base_salary numeric(12,2) DEFAULT 0;
ALTER TABLE public.payroll_runs ADD COLUMN IF NOT EXISTS allowances numeric(12,2) DEFAULT 0;
ALTER TABLE public.payroll_runs ADD COLUMN IF NOT EXISTS deductions numeric(12,2) DEFAULT 0;
ALTER TABLE public.payroll_runs ADD COLUMN IF NOT EXISTS net_salary numeric(12,2) DEFAULT 0;
ALTER TABLE public.payroll_runs ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending'::text;
ALTER TABLE public.payroll_runs ADD COLUMN IF NOT EXISTS pay_date date;
ALTER TABLE public.payroll_runs ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.payroll_runs ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.payroll_runs ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.permission_audit_log ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.permission_audit_log ADD COLUMN IF NOT EXISTS actor_id uuid;
ALTER TABLE public.permission_audit_log ADD COLUMN IF NOT EXISTS target_user_id uuid;
ALTER TABLE public.permission_audit_log ADD COLUMN IF NOT EXISTS permission_key text;
ALTER TABLE public.permission_audit_log ADD COLUMN IF NOT EXISTS old_value boolean;
ALTER TABLE public.permission_audit_log ADD COLUMN IF NOT EXISTS new_value boolean;
ALTER TABLE public.permission_audit_log ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS id uuid;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS full_name text DEFAULT ''::text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS avatar_url text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS status text DEFAULT 'active'::text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS national_id text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS address text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS occupation text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS parent_code text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS passport_no text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS company text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS qualification text;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS annual_income numeric;
ALTER TABLE public.progress_notes ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.progress_notes ADD COLUMN IF NOT EXISTS student_id uuid;
ALTER TABLE public.progress_notes ADD COLUMN IF NOT EXISTS teacher_id uuid;
ALTER TABLE public.progress_notes ADD COLUMN IF NOT EXISTS note text;
ALTER TABLE public.progress_notes ADD COLUMN IF NOT EXISTS tone text DEFAULT 'neutral'::text;
ALTER TABLE public.progress_notes ADD COLUMN IF NOT EXISTS note_date date DEFAULT CURRENT_DATE;
ALTER TABLE public.progress_notes ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.progress_notes ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.promotion_records ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.promotion_records ADD COLUMN IF NOT EXISTS batch_id uuid;
ALTER TABLE public.promotion_records ADD COLUMN IF NOT EXISTS student_id uuid;
ALTER TABLE public.promotion_records ADD COLUMN IF NOT EXISTS from_class_id uuid;
ALTER TABLE public.promotion_records ADD COLUMN IF NOT EXISTS to_class_id uuid;
ALTER TABLE public.promotion_records ADD COLUMN IF NOT EXISTS from_session text;
ALTER TABLE public.promotion_records ADD COLUMN IF NOT EXISTS to_session text;
ALTER TABLE public.promotion_records ADD COLUMN IF NOT EXISTS result text DEFAULT 'promoted'::text;
ALTER TABLE public.promotion_records ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.promotion_records ADD COLUMN IF NOT EXISTS created_by uuid;
ALTER TABLE public.promotion_records ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.resignations ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.resignations ADD COLUMN IF NOT EXISTS staff_id uuid;
ALTER TABLE public.resignations ADD COLUMN IF NOT EXISTS submitted_at date DEFAULT CURRENT_DATE;
ALTER TABLE public.resignations ADD COLUMN IF NOT EXISTS last_working_day date;
ALTER TABLE public.resignations ADD COLUMN IF NOT EXISTS reason text;
ALTER TABLE public.resignations ADD COLUMN IF NOT EXISTS manager_status text DEFAULT 'pending'::text;
ALTER TABLE public.resignations ADD COLUMN IF NOT EXISTS hr_status text DEFAULT 'pending'::text;
ALTER TABLE public.resignations ADD COLUMN IF NOT EXISTS clearance jsonb DEFAULT '{}'::jsonb;
ALTER TABLE public.resignations ADD COLUMN IF NOT EXISTS exit_interview jsonb;
ALTER TABLE public.resignations ADD COLUMN IF NOT EXISTS final_settlement_amount numeric;
ALTER TABLE public.resignations ADD COLUMN IF NOT EXISTS status text DEFAULT 'in_progress'::text;
ALTER TABLE public.resignations ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.resignations ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.route_stops ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.route_stops ADD COLUMN IF NOT EXISTS route_id uuid;
ALTER TABLE public.route_stops ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.route_stops ADD COLUMN IF NOT EXISTS sequence integer DEFAULT 1;
ALTER TABLE public.route_stops ADD COLUMN IF NOT EXISTS eta text;
ALTER TABLE public.route_stops ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.route_stops ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.route_stops ADD COLUMN IF NOT EXISTS estimated_minutes integer DEFAULT 0;
ALTER TABLE public.route_students ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.route_students ADD COLUMN IF NOT EXISTS route_id uuid;
ALTER TABLE public.route_students ADD COLUMN IF NOT EXISTS stop_id uuid;
ALTER TABLE public.route_students ADD COLUMN IF NOT EXISTS student_id uuid;
ALTER TABLE public.route_students ADD COLUMN IF NOT EXISTS pickup_time text;
ALTER TABLE public.route_students ADD COLUMN IF NOT EXISTS drop_time text;
ALTER TABLE public.route_students ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.route_students ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.shifts ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.shifts ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.shifts ADD COLUMN IF NOT EXISTS shift_type text DEFAULT 'fixed'::text;
ALTER TABLE public.shifts ADD COLUMN IF NOT EXISTS start_time time without time zone;
ALTER TABLE public.shifts ADD COLUMN IF NOT EXISTS end_time time without time zone;
ALTER TABLE public.shifts ADD COLUMN IF NOT EXISTS weekly_off text[] DEFAULT ARRAY['sunday'::text];
ALTER TABLE public.shifts ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS profile_id uuid;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS employee_code text;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS full_name text;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS address text;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS dob date;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS department text;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS designation text;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS employment_type text DEFAULT 'full_time'::text;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS join_date date DEFAULT CURRENT_DATE;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS reporting_manager_id uuid;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS status text DEFAULT 'active'::text;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS photo_url text;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS emergency_contact jsonb;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS bank_details jsonb;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS probation_end_date date;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS confirmation_status text DEFAULT 'confirmed'::text;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS blood_group text;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS medical_info jsonb;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS background_verification jsonb;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS exit_status text;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS skills text[] DEFAULT '{}'::text[];
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS qualifications jsonb;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS experience_years numeric;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS gender text;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS marital_status text;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS father_name text;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS mother_name text;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS biometric_id text;
ALTER TABLE public.staff ADD COLUMN IF NOT EXISTS staff_category text;
ALTER TABLE public.staff_documents ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.staff_documents ADD COLUMN IF NOT EXISTS staff_id uuid;
ALTER TABLE public.staff_documents ADD COLUMN IF NOT EXISTS doc_type text;
ALTER TABLE public.staff_documents ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.staff_documents ADD COLUMN IF NOT EXISTS file_url text;
ALTER TABLE public.staff_documents ADD COLUMN IF NOT EXISTS uploaded_at timestamp with time zone DEFAULT now();
ALTER TABLE public.staff_documents ADD COLUMN IF NOT EXISTS expiry_date date;
ALTER TABLE public.staff_documents ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.staff_documents ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.staff_employment_history ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.staff_employment_history ADD COLUMN IF NOT EXISTS staff_id uuid;
ALTER TABLE public.staff_employment_history ADD COLUMN IF NOT EXISTS event_type text;
ALTER TABLE public.staff_employment_history ADD COLUMN IF NOT EXISTS effective_date date;
ALTER TABLE public.staff_employment_history ADD COLUMN IF NOT EXISTS from_value text;
ALTER TABLE public.staff_employment_history ADD COLUMN IF NOT EXISTS to_value text;
ALTER TABLE public.staff_employment_history ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.staff_employment_history ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.staff_permissions ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.staff_permissions ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE public.staff_permissions ADD COLUMN IF NOT EXISTS permission_key text;
ALTER TABLE public.staff_permissions ADD COLUMN IF NOT EXISTS enabled boolean DEFAULT false;
ALTER TABLE public.staff_permissions ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.staff_permissions ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.staff_shifts ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.staff_shifts ADD COLUMN IF NOT EXISTS staff_id uuid;
ALTER TABLE public.staff_shifts ADD COLUMN IF NOT EXISTS shift_id uuid;
ALTER TABLE public.staff_shifts ADD COLUMN IF NOT EXISTS effective_from date DEFAULT CURRENT_DATE;
ALTER TABLE public.staff_shifts ADD COLUMN IF NOT EXISTS effective_to date;
ALTER TABLE public.staff_shifts ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.student_activity_log ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.student_activity_log ADD COLUMN IF NOT EXISTS student_id uuid;
ALTER TABLE public.student_activity_log ADD COLUMN IF NOT EXISTS event_type text;
ALTER TABLE public.student_activity_log ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.student_activity_log ADD COLUMN IF NOT EXISTS meta jsonb;
ALTER TABLE public.student_activity_log ADD COLUMN IF NOT EXISTS actor_id uuid;
ALTER TABLE public.student_activity_log ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.student_categories ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.student_categories ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.student_categories ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.student_categories ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.student_custom_fields ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.student_custom_fields ADD COLUMN IF NOT EXISTS label text;
ALTER TABLE public.student_custom_fields ADD COLUMN IF NOT EXISTS field_type text DEFAULT 'text'::text;
ALTER TABLE public.student_custom_fields ADD COLUMN IF NOT EXISTS options jsonb DEFAULT '[]'::jsonb;
ALTER TABLE public.student_custom_fields ADD COLUMN IF NOT EXISTS active boolean DEFAULT true;
ALTER TABLE public.student_custom_fields ADD COLUMN IF NOT EXISTS sort_order integer DEFAULT 0;
ALTER TABLE public.student_custom_fields ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.student_custom_fields ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS student_id uuid;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS first_name text;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS middle_name text;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS last_name text;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS category_id uuid;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS house text;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS religion text;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS caste text;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS sub_caste text;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS mother_tongue text;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS place_of_birth text;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS nationality text DEFAULT 'Indian'::text;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS aadhaar_no text;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS pen_sssm_id text;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS bpl boolean DEFAULT false;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS rte boolean DEFAULT false;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS biometric_id text;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS previous_school text;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS opening_due_balance numeric DEFAULT 0;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS bank_name text;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS bank_account text;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS bank_ifsc text;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS photo_url text;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS student_phone text;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS student_email text;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS custom jsonb DEFAULT '{}'::jsonb;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS updated_by uuid;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS dob date;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS current_address text;
ALTER TABLE public.student_details ADD COLUMN IF NOT EXISTS permanent_address text;
ALTER TABLE public.student_disciplinary ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.student_disciplinary ADD COLUMN IF NOT EXISTS student_id uuid;
ALTER TABLE public.student_disciplinary ADD COLUMN IF NOT EXISTS incident_date date DEFAULT CURRENT_DATE;
ALTER TABLE public.student_disciplinary ADD COLUMN IF NOT EXISTS category text DEFAULT 'general'::text;
ALTER TABLE public.student_disciplinary ADD COLUMN IF NOT EXISTS severity text DEFAULT 'minor'::text;
ALTER TABLE public.student_disciplinary ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.student_disciplinary ADD COLUMN IF NOT EXISTS action_taken text;
ALTER TABLE public.student_disciplinary ADD COLUMN IF NOT EXISTS status text DEFAULT 'open'::text;
ALTER TABLE public.student_disciplinary ADD COLUMN IF NOT EXISTS reported_by uuid;
ALTER TABLE public.student_disciplinary ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.student_disciplinary ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.student_documents ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.student_documents ADD COLUMN IF NOT EXISTS student_id uuid;
ALTER TABLE public.student_documents ADD COLUMN IF NOT EXISTS doc_type text DEFAULT 'other'::text;
ALTER TABLE public.student_documents ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.student_documents ADD COLUMN IF NOT EXISTS file_url text;
ALTER TABLE public.student_documents ADD COLUMN IF NOT EXISTS issued_date date;
ALTER TABLE public.student_documents ADD COLUMN IF NOT EXISTS expiry_date date;
ALTER TABLE public.student_documents ADD COLUMN IF NOT EXISTS verified boolean DEFAULT false;
ALTER TABLE public.student_documents ADD COLUMN IF NOT EXISTS uploaded_by uuid;
ALTER TABLE public.student_documents ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.student_documents ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.student_hostel ADD COLUMN IF NOT EXISTS student_id uuid;
ALTER TABLE public.student_hostel ADD COLUMN IF NOT EXISTS is_resident boolean DEFAULT false;
ALTER TABLE public.student_hostel ADD COLUMN IF NOT EXISTS hostel_block text;
ALTER TABLE public.student_hostel ADD COLUMN IF NOT EXISTS room_no text;
ALTER TABLE public.student_hostel ADD COLUMN IF NOT EXISTS bed_no text;
ALTER TABLE public.student_hostel ADD COLUMN IF NOT EXISTS warden_name text;
ALTER TABLE public.student_hostel ADD COLUMN IF NOT EXISTS warden_phone text;
ALTER TABLE public.student_hostel ADD COLUMN IF NOT EXISTS check_in_date date;
ALTER TABLE public.student_hostel ADD COLUMN IF NOT EXISTS check_out_date date;
ALTER TABLE public.student_hostel ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.student_hostel ADD COLUMN IF NOT EXISTS updated_by uuid;
ALTER TABLE public.student_hostel ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.student_hostel ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.student_medical ADD COLUMN IF NOT EXISTS student_id uuid;
ALTER TABLE public.student_medical ADD COLUMN IF NOT EXISTS blood_group text;
ALTER TABLE public.student_medical ADD COLUMN IF NOT EXISTS allergies text;
ALTER TABLE public.student_medical ADD COLUMN IF NOT EXISTS chronic_conditions text;
ALTER TABLE public.student_medical ADD COLUMN IF NOT EXISTS medications text;
ALTER TABLE public.student_medical ADD COLUMN IF NOT EXISTS disabilities text;
ALTER TABLE public.student_medical ADD COLUMN IF NOT EXISTS physician_name text;
ALTER TABLE public.student_medical ADD COLUMN IF NOT EXISTS physician_phone text;
ALTER TABLE public.student_medical ADD COLUMN IF NOT EXISTS emergency_contact_name text;
ALTER TABLE public.student_medical ADD COLUMN IF NOT EXISTS emergency_contact_phone text;
ALTER TABLE public.student_medical ADD COLUMN IF NOT EXISTS insurance_provider text;
ALTER TABLE public.student_medical ADD COLUMN IF NOT EXISTS insurance_number text;
ALTER TABLE public.student_medical ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.student_medical ADD COLUMN IF NOT EXISTS updated_by uuid;
ALTER TABLE public.student_medical ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.student_medical ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.student_medical ADD COLUMN IF NOT EXISTS height_cm numeric;
ALTER TABLE public.student_medical ADD COLUMN IF NOT EXISTS weight_kg numeric;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS profile_id uuid;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS class_id uuid;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS admission_no text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS admission_date date DEFAULT CURRENT_DATE;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS roll_no text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS gender text;
ALTER TABLE public.students ADD COLUMN IF NOT EXISTS status student_status DEFAULT 'active'::student_status;
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS class_id uuid;
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS code text;
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS short_name text;
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS category text;
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS subject_type text DEFAULT 'compulsory'::text;
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS nature text DEFAULT 'theory'::text;
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS credits numeric(5,2) DEFAULT 0;
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS weekly_periods integer DEFAULT 0;
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS pass_marks numeric(6,2) DEFAULT 33;
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS max_marks numeric(6,2) DEFAULT 100;
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS lab_required boolean DEFAULT false;
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS department text;
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS color text;
ALTER TABLE public.subjects ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
ALTER TABLE public.teacher_attendance ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.teacher_attendance ADD COLUMN IF NOT EXISTS teacher_id uuid;
ALTER TABLE public.teacher_attendance ADD COLUMN IF NOT EXISTS date date;
ALTER TABLE public.teacher_attendance ADD COLUMN IF NOT EXISTS status text DEFAULT 'present'::text;
ALTER TABLE public.teacher_attendance ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.teacher_attendance ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.teacher_attendance ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.teacher_attendance ADD COLUMN IF NOT EXISTS check_in_time timestamp with time zone;
ALTER TABLE public.teacher_attendance ADD COLUMN IF NOT EXISTS marked_by text DEFAULT 'self'::text;
ALTER TABLE public.teacher_attendance ADD COLUMN IF NOT EXISTS marked_by_user uuid;
ALTER TABLE public.teacher_attendance ADD COLUMN IF NOT EXISTS correction_reason text;
ALTER TABLE public.teacher_classes ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.teacher_classes ADD COLUMN IF NOT EXISTS teacher_id uuid;
ALTER TABLE public.teacher_classes ADD COLUMN IF NOT EXISTS class_id uuid;
ALTER TABLE public.teacher_classes ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.teacher_experience ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.teacher_experience ADD COLUMN IF NOT EXISTS teacher_id uuid;
ALTER TABLE public.teacher_experience ADD COLUMN IF NOT EXISTS employer text;
ALTER TABLE public.teacher_experience ADD COLUMN IF NOT EXISTS role text;
ALTER TABLE public.teacher_experience ADD COLUMN IF NOT EXISTS start_date date;
ALTER TABLE public.teacher_experience ADD COLUMN IF NOT EXISTS end_date date;
ALTER TABLE public.teacher_experience ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.teacher_experience ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.teacher_performance_reviews ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.teacher_performance_reviews ADD COLUMN IF NOT EXISTS teacher_id uuid;
ALTER TABLE public.teacher_performance_reviews ADD COLUMN IF NOT EXISTS period text;
ALTER TABLE public.teacher_performance_reviews ADD COLUMN IF NOT EXISTS rating numeric(3,1);
ALTER TABLE public.teacher_performance_reviews ADD COLUMN IF NOT EXISTS reviewer_id uuid;
ALTER TABLE public.teacher_performance_reviews ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.teacher_performance_reviews ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.teacher_performance_reviews ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.teacher_qualifications ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.teacher_qualifications ADD COLUMN IF NOT EXISTS teacher_id uuid;
ALTER TABLE public.teacher_qualifications ADD COLUMN IF NOT EXISTS degree text;
ALTER TABLE public.teacher_qualifications ADD COLUMN IF NOT EXISTS institution text;
ALTER TABLE public.teacher_qualifications ADD COLUMN IF NOT EXISTS year integer;
ALTER TABLE public.teacher_qualifications ADD COLUMN IF NOT EXISTS certification text;
ALTER TABLE public.teacher_qualifications ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.teacher_qualifications ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.teacher_subjects ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.teacher_subjects ADD COLUMN IF NOT EXISTS teacher_id uuid;
ALTER TABLE public.teacher_subjects ADD COLUMN IF NOT EXISTS class_id uuid;
ALTER TABLE public.teacher_subjects ADD COLUMN IF NOT EXISTS subject_id uuid;
ALTER TABLE public.teacher_subjects ADD COLUMN IF NOT EXISTS role text DEFAULT 'subject_teacher'::text;
ALTER TABLE public.teacher_subjects ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS full_name text;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS phone text;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS subject text;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS qualification text;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS experience_years integer DEFAULT 0;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS joined_date date DEFAULT CURRENT_DATE;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS status text DEFAULT 'active'::text;
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.teachers ADD COLUMN IF NOT EXISTS staff_id uuid;
ALTER TABLE public.timetable ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.timetable ADD COLUMN IF NOT EXISTS class_id uuid;
ALTER TABLE public.timetable ADD COLUMN IF NOT EXISTS subject_id uuid;
ALTER TABLE public.timetable ADD COLUMN IF NOT EXISTS teacher_id uuid;
ALTER TABLE public.timetable ADD COLUMN IF NOT EXISTS day_of_week smallint;
ALTER TABLE public.timetable ADD COLUMN IF NOT EXISTS start_time time without time zone;
ALTER TABLE public.timetable ADD COLUMN IF NOT EXISTS end_time time without time zone;
ALTER TABLE public.timetable ADD COLUMN IF NOT EXISTS room text;
ALTER TABLE public.timetable ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.training_attendance ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.training_attendance ADD COLUMN IF NOT EXISTS program_id uuid;
ALTER TABLE public.training_attendance ADD COLUMN IF NOT EXISTS staff_id uuid;
ALTER TABLE public.training_attendance ADD COLUMN IF NOT EXISTS attended boolean DEFAULT false;
ALTER TABLE public.training_attendance ADD COLUMN IF NOT EXISTS feedback text;
ALTER TABLE public.training_attendance ADD COLUMN IF NOT EXISTS rating integer;
ALTER TABLE public.training_attendance ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.training_programs ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.training_programs ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.training_programs ADD COLUMN IF NOT EXISTS program_type text DEFAULT 'workshop'::text;
ALTER TABLE public.training_programs ADD COLUMN IF NOT EXISTS provider text;
ALTER TABLE public.training_programs ADD COLUMN IF NOT EXISTS start_date date;
ALTER TABLE public.training_programs ADD COLUMN IF NOT EXISTS end_date date;
ALTER TABLE public.training_programs ADD COLUMN IF NOT EXISTS cost numeric DEFAULT 0;
ALTER TABLE public.training_programs ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE public.training_programs ADD COLUMN IF NOT EXISTS skill_tags text[] DEFAULT '{}'::text[];
ALTER TABLE public.training_programs ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.transport_routes ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.transport_routes ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.transport_routes ADD COLUMN IF NOT EXISTS vehicle_id uuid;
ALTER TABLE public.transport_routes ADD COLUMN IF NOT EXISTS driver_id uuid;
ALTER TABLE public.transport_routes ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.transport_routes ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.transport_routes ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.travel_requests ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.travel_requests ADD COLUMN IF NOT EXISTS staff_id uuid;
ALTER TABLE public.travel_requests ADD COLUMN IF NOT EXISTS destination text;
ALTER TABLE public.travel_requests ADD COLUMN IF NOT EXISTS start_date date;
ALTER TABLE public.travel_requests ADD COLUMN IF NOT EXISTS end_date date;
ALTER TABLE public.travel_requests ADD COLUMN IF NOT EXISTS purpose text;
ALTER TABLE public.travel_requests ADD COLUMN IF NOT EXISTS advance_amount numeric DEFAULT 0;
ALTER TABLE public.travel_requests ADD COLUMN IF NOT EXISTS settlement_amount numeric;
ALTER TABLE public.travel_requests ADD COLUMN IF NOT EXISTS status text DEFAULT 'pending'::text;
ALTER TABLE public.travel_requests ADD COLUMN IF NOT EXISTS settled_at date;
ALTER TABLE public.travel_requests ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.user_roles ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.user_roles ADD COLUMN IF NOT EXISTS user_id uuid;
ALTER TABLE public.user_roles ADD COLUMN IF NOT EXISTS role app_role;
ALTER TABLE public.user_roles ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.vehicle_documents ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.vehicle_documents ADD COLUMN IF NOT EXISTS vehicle_id uuid;
ALTER TABLE public.vehicle_documents ADD COLUMN IF NOT EXISTS doc_kind text;
ALTER TABLE public.vehicle_documents ADD COLUMN IF NOT EXISTS title text;
ALTER TABLE public.vehicle_documents ADD COLUMN IF NOT EXISTS file_path text;
ALTER TABLE public.vehicle_documents ADD COLUMN IF NOT EXISTS issue_date date;
ALTER TABLE public.vehicle_documents ADD COLUMN IF NOT EXISTS expiry_date date;
ALTER TABLE public.vehicle_documents ADD COLUMN IF NOT EXISTS uploaded_by uuid;
ALTER TABLE public.vehicle_documents ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.vehicle_documents ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.vehicle_documents ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.vehicle_maintenance ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.vehicle_maintenance ADD COLUMN IF NOT EXISTS vehicle_id uuid;
ALTER TABLE public.vehicle_maintenance ADD COLUMN IF NOT EXISTS service_date date;
ALTER TABLE public.vehicle_maintenance ADD COLUMN IF NOT EXISTS service_type text;
ALTER TABLE public.vehicle_maintenance ADD COLUMN IF NOT EXISTS cost numeric(12,2) DEFAULT 0;
ALTER TABLE public.vehicle_maintenance ADD COLUMN IF NOT EXISTS vendor text;
ALTER TABLE public.vehicle_maintenance ADD COLUMN IF NOT EXISTS next_due_date date;
ALTER TABLE public.vehicle_maintenance ADD COLUMN IF NOT EXISTS notes text;
ALTER TABLE public.vehicle_maintenance ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.vehicle_maintenance ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.vehicle_positions ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.vehicle_positions ADD COLUMN IF NOT EXISTS vehicle_id uuid;
ALTER TABLE public.vehicle_positions ADD COLUMN IF NOT EXISTS lat numeric(9,6);
ALTER TABLE public.vehicle_positions ADD COLUMN IF NOT EXISTS lng numeric(9,6);
ALTER TABLE public.vehicle_positions ADD COLUMN IF NOT EXISTS speed_kph numeric(6,2);
ALTER TABLE public.vehicle_positions ADD COLUMN IF NOT EXISTS heading numeric(5,2);
ALTER TABLE public.vehicle_positions ADD COLUMN IF NOT EXISTS gps_connected boolean DEFAULT true;
ALTER TABLE public.vehicle_positions ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
ALTER TABLE public.visitor_logs ADD COLUMN IF NOT EXISTS id uuid DEFAULT gen_random_uuid();
ALTER TABLE public.visitor_logs ADD COLUMN IF NOT EXISTS name text;
ALTER TABLE public.visitor_logs ADD COLUMN IF NOT EXISTS purpose text;
ALTER TABLE public.visitor_logs ADD COLUMN IF NOT EXISTS meeting_person text;
ALTER TABLE public.visitor_logs ADD COLUMN IF NOT EXISTS department text;
ALTER TABLE public.visitor_logs ADD COLUMN IF NOT EXISTS id_reference text;
ALTER TABLE public.visitor_logs ADD COLUMN IF NOT EXISTS photo_url text;
ALTER TABLE public.visitor_logs ADD COLUMN IF NOT EXISTS check_in timestamp with time zone DEFAULT now();
ALTER TABLE public.visitor_logs ADD COLUMN IF NOT EXISTS check_out timestamp with time zone;
ALTER TABLE public.visitor_logs ADD COLUMN IF NOT EXISTS created_at timestamp with time zone DEFAULT now();
ALTER TABLE public.visitor_logs ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone DEFAULT now();
